-- ============================================================================
-- SIMONA — hardening pass
--   1. Server-side order_code generation (no client-side race)
--   2. updated_at columns + auto-update triggers
--   3. Indexes for the common filters/sorts
-- Paste into the Supabase SQL editor and run once.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. order_code is generated by the database, not the app.
-- ----------------------------------------------------------------------------
create sequence if not exists public.order_code_seq;

-- Align the sequence with any existing ORD-### codes so the next one is max+1.
select setval(
  'public.order_code_seq',
  greatest(
    1,
    coalesce(
      (select max((substring(order_code from 'ORD-(\d+)'))::int)
         from public.orders
        where order_code ~ '^ORD-\d+$'),
      0
    ) + 1
  ),
  false
);

create or replace function public.set_order_code()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.order_code is null or new.order_code = '' then
    new.order_code :=
      'ORD-' || lpad(nextval('public.order_code_seq')::text, 3, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists trg_set_order_code on public.orders;
create trigger trg_set_order_code
  before insert on public.orders
  for each row execute function public.set_order_code();

-- ----------------------------------------------------------------------------
-- 2. updated_at columns kept fresh by the moddatetime extension.
-- ----------------------------------------------------------------------------
create extension if not exists moddatetime with schema extensions;

alter table public.clients add column if not exists updated_at timestamptz not null default now();
alter table public.orders  add column if not exists updated_at timestamptz not null default now();
alter table public.tasks   add column if not exists updated_at timestamptz not null default now();

drop trigger if exists handle_updated_at on public.clients;
create trigger handle_updated_at
  before update on public.clients
  for each row execute function extensions.moddatetime(updated_at);

drop trigger if exists handle_updated_at on public.orders;
create trigger handle_updated_at
  before update on public.orders
  for each row execute function extensions.moddatetime(updated_at);

drop trigger if exists handle_updated_at on public.tasks;
create trigger handle_updated_at
  before update on public.tasks
  for each row execute function extensions.moddatetime(updated_at);

-- ----------------------------------------------------------------------------
-- 3. Indexes for the dashboard's hot paths.
-- ----------------------------------------------------------------------------
create index if not exists idx_orders_client_name on public.orders (client_name);
create index if not exists idx_orders_status      on public.orders (status);
create index if not exists idx_orders_created_at  on public.orders (created_at desc);
create index if not exists idx_tasks_due_date     on public.tasks (due_date);
create index if not exists idx_clients_created_at on public.clients (created_at desc);

-- ============================================================================
-- End of hardening migration.
-- ============================================================================
