"use server";

import { revalidatePath } from "next/cache";

import { createClient as createSupabase } from "@/lib/supabase/server";

// All writes target the BASE orders table with return=minimal (no .select()),
// since the financial columns aren't API-readable on the base table.

export interface NewOrderInput {
  // order_code is generated by a DB trigger (see migration 0002), not the app.
  client_name: string;
  order_type: string;
  item: string;
  collection: string;
  amount: number;
  payment_status: string;
  order_date: string | null;
  due_date: string | null;
  status: string;
  assigned_to: string;
  notes: string;
}

export async function createOrder(input: NewOrderInput) {
  const supabase = await createSupabase();
  const { error } = await supabase.from("orders").insert(input);
  if (error) throw new Error(error.message);
  revalidatePath("/orders");
}

export async function updateOrderStatus(id: string, status: string) {
  const supabase = await createSupabase();
  const { error } = await supabase.from("orders").update({ status }).eq("id", id);
  if (error) throw new Error(error.message);
  revalidatePath("/orders");
}

export async function saveOrderOpsNote(id: string, ops_note: string) {
  const supabase = await createSupabase();
  const { error } = await supabase
    .from("orders")
    .update({ ops_note })
    .eq("id", id);
  if (error) throw new Error(error.message);
  revalidatePath("/orders");
}

export async function deleteOrder(id: string) {
  const supabase = await createSupabase();
  const { error } = await supabase.from("orders").delete().eq("id", id);
  if (error) throw new Error(error.message);
  revalidatePath("/orders");
}
